#!/usr/bin/env bash
# =============================================================================
# gen-vault — create an encrypted Ansible Vault with strong random credentials
# =============================================================================
# Called by `make vault-init`. Generates the Wazuh secrets, writes them to the
# vault file and encrypts it in place.
#
# The result is GITIGNORED and stays on this machine. This repository is public,
# and published ciphertext is a permanent offline target whose only protection is
# a passphrase. Each clone generates its own vault; only vault.yml.example — the
# variable names, with no values — is committed.
#
# Every value here is generated. There is no overlay credential to paste in:
# WireGuard keys are created on each host by `wg genkey` and never leave it.
# =============================================================================
set -euo pipefail

VAULT_FILE="${1:?usage: gen-vault.sh <path-to-vault.yml> [--vault-password-file FILE]}"
shift
VAULT_PW_ARGS=("$@")

if [[ -e "$VAULT_FILE" ]]; then
	printf 'Refusing to overwrite an existing vault: %s\n\n' "$VAULT_FILE" >&2
	printf 'To change a value:   make vault-edit\n' >&2
	printf 'To start over:       rm %s && make vault-init\n' "$VAULT_FILE" >&2
	printf '\nDeleting a vault whose password you still know loses nothing but\n' >&2
	printf 'the passwords themselves. Deleting one after Wazuh has already\n' >&2
	printf 'initialised its security index means you can no longer log in —\n' >&2
	printf 'recover with: make rotate-passwords\n' >&2
	exit 1
fi

# -----------------------------------------------------------------------------
# Generators
# -----------------------------------------------------------------------------
# Alphanumeric by design. These values are interpolated into a Docker Compose
# file and several YAML documents, where `$` invites Compose variable
# substitution and backticks and quotes invite shell surprises. 24 alphanumeric
# characters is ~140 bits — losing the symbol classes costs nothing that matters.
rand_alnum() {
	LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "${1:-24}"
}

rand_hex() {
	LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c "${1:-32}"
}

# The Wazuh server API enforces its own complexity rule: 8-64 characters with at
# least one uppercase, one lowercase, one digit and one symbol. A password that
# fails it is rejected, and the symptom is a dashboard whose Agents view is
# simply empty. Constructing the classes explicitly is more reliable than
# generating and hoping.
rand_api_password() {
	printf '%s%s%s%s' \
		"$(rand_alnum 20)" \
		"$(LC_ALL=C tr -dc '[:upper:]' < /dev/urandom | head -c 1)" \
		"$(LC_ALL=C tr -dc '0-9' < /dev/urandom | head -c 1)" \
		'.-'
}

umask 077

cat > "$VAULT_FILE" <<EOF
---
# =============================================================================
# ENCRYPTED BY ANSIBLE VAULT — generated by scripts/gen-vault.sh
# =============================================================================
# GITIGNORED. This file stays on this machine; see .gitignore for why.
#
#   make vault-show    read it
#   make vault-edit    change it
#
# Consumed by inventory/group_vars/all/vars.yml, which is the only file that
# references these names — so \`grep vault_ vars.yml\` is a complete list of
# where the secrets are used.
# =============================================================================

# Wazuh indexer administrator. This is the dashboard login.
vault_wazuh_indexer_password: "$(rand_alnum 24)"

# Service account the dashboard uses to reach the indexer. Not a human login.
vault_wazuh_dashboard_password: "$(rand_alnum 24)"

# Wazuh server API account (wazuh-wui). Must satisfy the API's complexity rule.
vault_wazuh_api_password: "$(rand_api_password)"

# Manager cluster key. Unused single-node, but upstream's demo value is public.
vault_wazuh_cluster_key: "$(rand_hex 32)"

EOF

printf 'Wrote %s\n' "$VAULT_FILE"
printf 'Encrypting — choose a vault password you will not lose:\n\n'

ansible-vault encrypt "${VAULT_PW_ARGS[@]}" "$VAULT_FILE"

printf '\nDone. The file is encrypted and safe to commit.\n'
printf 'Read the generated dashboard password with:  make vault-show\n'
